import pyxel
def lvl1(spike_y_min): #saut de block (+60/55 en x) ; saut de 2spike (+10 en x)
    return [
        #1
        {'x': 200, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 280, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 360, 'y': spike_y_min, 'type': 'spike', 'turned': False},

        #2
        {'x': 440, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 450, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 540, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 550, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 560, 'y': spike_y_min, 'type': 'spike', 'turned': False},

        #3
        {'x': 640, 'y': spike_y_min, 'type': 'block'},
        {'x': 700, 'y': spike_y_min - 16, 'type': 'block'},
        {'x': 700, 'y': spike_y_min, 'type': 'block'},
        {'x': 755, 'y': spike_y_min - 32, 'type': 'block'},
        {'x': 755, 'y': spike_y_min - 16, 'type': 'block'},
        {'x': 755, 'y': spike_y_min, 'type': 'block'},

        #4
        {'x': 800, 'y': spike_y_min - 48, 'type': 'block'},
        {'x': 816, 'y': spike_y_min - 48, 'type': 'block'},
        {'x': 832, 'y': spike_y_min - 48, 'type': 'block'},
        {'x': 810, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 832, 'y': spike_y_min - 64, 'type': 'spike', 'turned': False},
        
        #5
        {'x': 870, 'y': spike_y_min - 32, 'type': 'block'},
        {'x': 870, 'y': spike_y_min - 16, 'type': 'block'},
        {'x': 870, 'y': spike_y_min, 'type': 'block'},
        {'x': 902, 'y': spike_y_min - 16, 'type': 'block'},
        {'x': 902, 'y': spike_y_min, 'type': 'block'},
        {'x': 934, 'y': spike_y_min, 'type': 'block'},
        {'x': 886, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 918, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        
        #6
        {'x': 1060, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 1070, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 1120, 'y': spike_y_min - 16, 'type': 'block'},
        {'x': 1120, 'y': spike_y_min - 32, 'type': 'spike', 'turned': False},
        {'x': 1165, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 1175, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 1185, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 1270, 'y': spike_y_min - 16, 'type': 'block'},
        {'x': 1270, 'y': spike_y_min, 'type': 'block'},
        {'x': 1300, 'y': spike_y_min, 'type': 'block'},
        #fait
        #7
        {'x': 1350, 'y': spike_y_min - 16, 'type': 'block'},
        {'x': 1366, 'y': spike_y_min - 16, 'type': 'block'},
        {'x': 1382, 'y': spike_y_min - 16, 'type': 'block'},
        {'x': 1398, 'y': spike_y_min - 16, 'type': 'block'},
        {'x': 1414, 'y': spike_y_min - 16, 'type': 'block'},
        {'x': 1350, 'y': spike_y_min - 32, 'type': 'spike', 'turned': False},
        {'x': 1366, 'y': spike_y_min - 32, 'type': 'spike', 'turned': False},
        {'x': 1382, 'y': spike_y_min - 32, 'type': 'spike', 'turned': False},
        {'x': 1398, 'y': spike_y_min - 32, 'type': 'spike', 'turned': False},
        {'x': 1414, 'y': spike_y_min - 32, 'type': 'spike', 'turned': False},
        {'x': 1480, 'y': spike_y_min, 'type': 'block'},
        {'x': 1480, 'y': spike_y_min - 16, 'type': 'block'},
        {'x': 1350+193, 'y': spike_y_min - 16, 'type': 'block'},
        {'x': 1366+193, 'y': spike_y_min - 16, 'type': 'block'},
        {'x': 1382+193, 'y': spike_y_min - 16, 'type': 'block'},
        {'x': 1398+193, 'y': spike_y_min - 16, 'type': 'block'},
        {'x': 1414+193, 'y': spike_y_min - 16, 'type': 'block'},
        {'x': 1350+193, 'y': spike_y_min - 32, 'type': 'spike', 'turned': False},
        {'x': 1366+193, 'y': spike_y_min - 32, 'type': 'spike', 'turned': False},
        {'x': 1382+193, 'y': spike_y_min - 32, 'type': 'spike', 'turned': False},
        {'x': 1398+193, 'y': spike_y_min - 32, 'type': 'spike', 'turned': False},
        {'x': 1414+193, 'y': spike_y_min - 32, 'type': 'spike', 'turned': False},
        #8
        {'x': 1694, 'y': spike_y_min, 'type': 'block'},
        {'x': 1694, 'y': spike_y_min - 16, 'type': 'block'},
        {'x': 1694, 'y': spike_y_min - 53, 'type': 'block'},
        {'x': 1694+100, 'y': spike_y_min, 'type': 'block'},
        {'x': 1694+100, 'y': spike_y_min - 16, 'type': 'block'},
        {'x': 1694+100, 'y': spike_y_min - 53, 'type': 'block'},
        {'x': 1694+200, 'y': spike_y_min, 'type': 'block'},
        {'x': 1694+200, 'y': spike_y_min - 16, 'type': 'block'},
        {'x': 1694+200, 'y': spike_y_min - 53, 'type': 'block'},
        {'x': 1694, 'y': spike_y_min - 69, 'type': 'spike', 'turned': False},
        {'x': 1694+100, 'y': spike_y_min - 69, 'type': 'spike', 'turned': False},
        {'x': 1694+200, 'y': spike_y_min - 69, 'type': 'spike', 'turned': False},
        #9
        {'x': 1994, 'y': spike_y_min, 'type': 'block'},
        {'x': 2044, 'y': spike_y_min - 16, 'type': 'block'},
        {'x': 2044, 'y': spike_y_min, 'type': 'block'},
        {'x': 2084, 'y': spike_y_min - 32, 'type': 'block'},
        {'x': 2084+16, 'y': spike_y_min - 32, 'type': 'block'},
        {'x': 2084+32, 'y': spike_y_min - 32, 'type': 'block'},
        {'x': 2084+48, 'y': spike_y_min - 32, 'type': 'block'},
        {'x': 2084+64, 'y': spike_y_min - 32, 'type': 'block'},
        {'x': 2084+80, 'y': spike_y_min - 32, 'type': 'block'},
        {'x': 2084+96, 'y': spike_y_min - 32, 'type': 'block'},
        {'x': 2084+16, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 2084+32, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 2084+48, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 2084+64, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 2084+80, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 2084+96, 'y': spike_y_min, 'type': 'spike', 'turned': False},
      #10
        {'x': 2196, 'y': spike_y_min - 32, 'type': 'block'},
        {'x': 2125, 'y': spike_y_min - 48, 'type': 'spike', 'turned': False},
        {'x': 2135, 'y': spike_y_min - 48, 'type': 'spike', 'turned': False},
        {'x': 2145, 'y': spike_y_min - 48, 'type': 'spike', 'turned': False},
        {'x': 2196+48, 'y': spike_y_min - 32, 'type': 'block'},
        {'x': 2196+70, 'y': spike_y_min - 12, 'type': 'block'},
        {'x': 2196+86, 'y': spike_y_min - 12, 'type': 'block'},
        {'x': 2282+16, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 2282+32, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 2314+10, 'y': spike_y_min - 32, 'type': 'block'},
        {'x': 2314+32, 'y': spike_y_min - 12, 'type': 'block'},
        {'x': 2314+48, 'y': spike_y_min - 12, 'type': 'block'},
        {'x': 2384+20, 'y': spike_y_min - 32, 'type': 'block'},
        {'x': 2384+42, 'y': spike_y_min - 12, 'type': 'block'},
        {'x': 2384+58, 'y': spike_y_min - 12, 'type': 'block'},
        #11 (clubstep)
        {'x': 2500, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 2510, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 2520, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 2510, 'y': spike_y_min - 64-16, 'type': 'block'},
        {'x': 2510, 'y': spike_y_min - 80-16, 'type': 'block'},
        {'x': 2510, 'y': spike_y_min - 96-16, 'type': 'block'},
        {'x': 2526, 'y': spike_y_min - 64-16, 'type': 'block'},
        {'x': 2542, 'y': spike_y_min - 64-16, 'type': 'block'},
        {'x': 2542, 'y': spike_y_min - 80-16, 'type': 'block'},
        {'x': 2542, 'y': spike_y_min - 96-16, 'type': 'block'},
        {'x': 2526, 'y': spike_y_min - 96-16, 'type': 'block'},
        {'x': 2494, 'y': spike_y_min - 64-16, 'type': 'block'},
        {'x': 2478, 'y': spike_y_min - 64-16, 'type': 'block'},
        {'x': 2478, 'y': spike_y_min - 80-16, 'type': 'block'},
        {'x': 2478, 'y': spike_y_min - 96-16, 'type': 'block'},
        {'x': 2494, 'y': spike_y_min - 96-16, 'type': 'block'},
        {'x': 2494, 'y': spike_y_min - 80-16, 'type': 'orb', 'used': False},
        {'x': 2526, 'y': spike_y_min - 80-16, 'type': 'orb', 'used': False},
        
        {'x': 2500+150, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 2510+150, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 2520+150, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 2510+150, 'y': spike_y_min - 64-16, 'type': 'block'},
        {'x': 2510+150, 'y': spike_y_min - 80-16, 'type': 'block'},
        {'x': 2510+150, 'y': spike_y_min - 96-16, 'type': 'block'},
        {'x': 2526+150, 'y': spike_y_min - 64-16, 'type': 'block'},
        {'x': 2542+150, 'y': spike_y_min - 64-16, 'type': 'block'},
        {'x': 2542+150, 'y': spike_y_min - 80-16, 'type': 'block'},
        {'x': 2542+150, 'y': spike_y_min - 96-16, 'type': 'block'},
        {'x': 2526+150, 'y': spike_y_min - 96-16, 'type': 'block'},
        {'x': 2494+150, 'y': spike_y_min - 64-16, 'type': 'block'},
        {'x': 2478+150, 'y': spike_y_min - 64-16, 'type': 'block'},
        {'x': 2478+150, 'y': spike_y_min - 80-16, 'type': 'block'},
        {'x': 2478+150, 'y': spike_y_min - 96-16, 'type': 'block'},
        {'x': 2494+150, 'y': spike_y_min - 96-16, 'type': 'block'},
        {'x': 2494+150, 'y': spike_y_min - 80-16, 'type': 'orb', 'used': False},
        {'x': 2526+150, 'y': spike_y_min - 80-16, 'type': 'orb', 'used': False},
        {'x': 2510, 'y': spike_y_min - 48-16, 'type': 'spike', 'turned': True},
        {'x': 2494, 'y': spike_y_min - 48-16, 'type': 'spike', 'turned': True},
        {'x': 2526, 'y': spike_y_min - 48-16, 'type': 'spike', 'turned': True},
        {'x': 2510+150, 'y': spike_y_min - 48-16, 'type': 'spike', 'turned': True},
        {'x': 2494+150, 'y': spike_y_min - 48-16, 'type': 'spike', 'turned': True},
        {'x': 2526+150, 'y': spike_y_min - 48-16, 'type': 'spike', 'turned': True},
        {'x': 2510, 'y': spike_y_min - -128, 'type': 'block'},
        {'x': 2510, 'y': spike_y_min - 128-16, 'type': 'block'},
        {'x': 2510, 'y': spike_y_min - 128-32, 'type': 'block'},
        {'x': 2526, 'y': spike_y_min - 128, 'type': 'block'},
        {'x': 2526, 'y': spike_y_min - 128-16, 'type': 'block'},
        {'x': 2526, 'y': spike_y_min - 128-32, 'type': 'block'},
        {'x': 2494, 'y': spike_y_min - 128, 'type': 'block'},
        {'x': 2494, 'y': spike_y_min - 128-16, 'type': 'block'},
        {'x': 2494, 'y': spike_y_min - 128-32, 'type': 'block'},
        
        {'x': 2510+150, 'y': spike_y_min - -128, 'type': 'block'},
        {'x': 2510+150, 'y': spike_y_min - 128-16, 'type': 'block'},
        {'x': 2510+150, 'y': spike_y_min - 128-32, 'type': 'block'},
        {'x': 2526+150, 'y': spike_y_min - 128, 'type': 'block'},
        {'x': 2526+150, 'y': spike_y_min - 128-16, 'type': 'block'},
        {'x': 2526+150, 'y': spike_y_min - 128-32, 'type': 'block'},
        {'x': 2494+150, 'y': spike_y_min - 128, 'type': 'block'},
        {'x': 2494+150, 'y': spike_y_min - 128-16, 'type': 'block'},
        {'x': 2494+150, 'y': spike_y_min - 128-32, 'type':
            'block'},
        {'x': 2510+32, 'y': spike_y_min - 128, 'type': 'spike', 'turned': False},
        {'x': 2510-32, 'y': spike_y_min - 128, 'type': 'spike', 'turned': False},
        {'x': 2542+150, 'y': spike_y_min - 128, 'type': 'spike', 'turned': False},
        {'x': 2478+150, 'y': spike_y_min - 128, 'type': 'spike', 'turned': False},
        
    ],2700
def lvl2(spike_y_min): #saut de block (+60/55 en x) ; saut de 2spike (+10 en x)
    return [
        {'x': 250, 'y': spike_y_min-20, 'type': 'orb', 'used': False},
        {'x': 250, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 250-16, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 250-32, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 250+16, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 250+32, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        
        {'x': 250+250, 'y': spike_y_min-20, 'type': 'orb', 'used': False},
        {'x': 250+250, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 250-16+250, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 250-32+250, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 250+16+250, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 250+32+250, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 640, 'y': spike_y_min, 'type': 'block'},
        {'x': 700, 'y': spike_y_min - 16, 'type': 'block'},
        {'x': 700, 'y': spike_y_min, 'type': 'block'},
        {'x': 755, 'y': spike_y_min - 32, 'type': 'block'},
        {'x': 755, 'y': spike_y_min - 16, 'type': 'block'},
        {'x': 755, 'y': spike_y_min, 'type': 'block'},
        {'x': 810, 'y': spike_y_min - 48, 'type': 'block'},
        {'x': 810, 'y': spike_y_min - 32, 'type': 'block'},
        {'x': 810, 'y': spike_y_min - 16, 'type': 'block'},
        {'x': 810, 'y': spike_y_min, 'type': 'block'},
        {'x': 865, 'y': spike_y_min - 64, 'type': 'block'},
        {'x': 865, 'y': spike_y_min - 48, 'type': 'block'},
        {'x': 865, 'y': spike_y_min - 32, 'type': 'block'},
        {'x': 865, 'y': spike_y_min - 16, 'type': 'block'},
        {'x': 865, 'y': spike_y_min, 'type': 'block'},
        {'x': 920, 'y': spike_y_min - 80, 'type': 'orb', 'used': False},
        {'x': 945, 'y': spike_y_min, 'type': 'orb', 'used': False},
        {'x': 950+16, 'y': spike_y_min - 80, 'type': 'block'},
        {'x': 950+16, 'y': spike_y_min - 96, 'type': 'block'},
        {'x': 950+16, 'y': spike_y_min - 112, 'type': 'spike', 'turned': False},
        {'x': 960, 'y': spike_y_min , 'type': 'spike', 'turned': False},
        {'x': 960+15, 'y': spike_y_min , 'type': 'spike', 'turned': False},
        {'x': 960+30, 'y': spike_y_min , 'type': 'spike', 'turned': False},
        {'x': 1075, 'y': spike_y_min-16, 'type': 'orb', 'used': False},
        {'x': 1120+20, 'y': spike_y_min-38, 'type': 'orb', 'used': False},
        {'x': 1165+20, 'y': spike_y_min-56, 'type': 'orb', 'used': False},
        {'x': 1210+35, 'y': spike_y_min-56, 'type': 'orb', 'used': False},
        
        
        
        
        
        {'x': 1100, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 1100+15, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 1100+30, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 1100+45, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 1100+60, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 1100+75, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 1100+90, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 1100+105, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 1100+120, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 1100+135, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 1100+150, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 1100+165, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 1100+180, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 1100+195, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 1295+32, 'y': spike_y_min, 'type': 'block'},
        {'x': 1295+32, 'y': spike_y_min-16, 'type': 'block'},
        {'x': 1295+32, 'y': spike_y_min-32, 'type': 'block'},
        {'x': 1295+32, 'y': spike_y_min-48, 'type': 'block'},
        {'x': 1295+32, 'y': spike_y_min-64, 'type': 'spike', 'turned': False},
        {'x': 1295+32, 'y': spike_y_min-112-64, 'type': 'block'},
        {'x': 1295+32, 'y': spike_y_min-112-48, 'type': 'block'},
        {'x': 1295+32, 'y': spike_y_min-112-32, 'type': 'block'},
        {'x': 1295+32, 'y': spike_y_min-112-16, 'type': 'block'},
        {'x': 1295+32, 'y': spike_y_min-112, 'type': 'spike', 'turned': True},
        {'x': 1350+50, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 1360+50, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        {'x': 1370+50, 'y': spike_y_min, 'type': 'spike', 'turned': False},
        
    ],2000
